name: Generate Timestamp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Timestamp
        id: timestamp
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Create timestamp file
        run: echo "$TIMESTAMP" > timestamp.txt

      - name: Commit timestamp file
        run: |
          git config --global user.name 'kironroy'
          git config --global user.email 'kironroydev@outlook.com'
          git add timestamp.txt
          git commit -m "Update timestamp"
          git push --set-upstream origin main
