name: Add Commit Timestamp

on:
  push:
    branches:
      - main

jobs:
  add-timestamp:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3

      - name: Get Commit Timestamp
        id: commit_time
        run: |
        TIMESTAMP=$(git log -1 --format='%cd' --date=format:'%Y-%m-%d %H:%M:%S')
        echo "timestamp=$TIMESTAMP" >> $GITHUB_OUTPUT


      - name: Use Timestamp
        run: echo "Commit timestamp is ${{ steps.commit_time.outputs.timestamp }}"
